"""Tests for the env_init plugin."""

import pytest
from pathlib import Path
from scaffy.plugins.builtin.env_init import EnvInitPlugin
from scaffy.plugins.base import PluginError
from scaffy.plugins.registry import clear_registry


@pytest.fixture(autouse=True)
def _clean_registry():
    yield
    clear_registry()


@pytest.fixture()
def plugin():
    return EnvInitPlugin()


@pytest.fixture()
def base_context(tmp_path):
    return {
        "output_dir": tmp_path,
        "template": {
            "env_vars": [
                "DATABASE_URL",
                {"key": "SECRET_KEY", "default": "changeme"},
                {"key": "DEBUG", "default": "false"},
            ]
        },
    }


def test_env_example_creates_file(plugin, base_context, tmp_path):
    plugin.run(base_context)
    assert (tmp_path / ".env.example").exists()


def test_env_example_plain_string_key(plugin, base_context, tmp_path):
    plugin.run(base_context)
    content = (tmp_path / ".env.example").read_text()
    assert "DATABASE_URL=" in content


def test_env_example_dict_entry_with_default(plugin, base_context, tmp_path):
    plugin.run(base_context)
    content = (tmp_path / ".env.example").read_text()
    assert "SECRET_KEY=changeme" in content


def test_env_example_dict_entry_no_default(plugin, tmp_path):
    ctx = {
        "output_dir": tmp_path,
        "template": {"env_vars": [{"key": "PORT"}]},
    }
    plugin.run(ctx)
    content = (tmp_path / ".env.example").read_text()
    assert "PORT=" in content


def test_env_example_header_comment(plugin, base_context, tmp_path):
    plugin.run(base_context)
    content = (tmp_path / ".env.example").read_text()
    assert content.startswith("# Auto-generated by scaffy")


def test_env_example_skips_when_no_vars(plugin, tmp_path):
    ctx = {"output_dir": tmp_path, "template": {}}
    plugin.run(ctx)
    assert not (tmp_path / ".env.example").exists()


def test_env_example_raises_on_missing_key_field(plugin, tmp_path):
    ctx = {
        "output_dir": tmp_path,
        "template": {"env_vars": [{"default": "oops"}]},
    }
    with pytest.raises(PluginError, match="missing 'key'"):
        plugin.run(ctx)


def test_env_example_raises_on_bad_entry_type(plugin, tmp_path):
    ctx = {
        "output_dir": tmp_path,
        "template": {"env_vars": [42]},
    }
    with pytest.raises(PluginError, match="unsupported env_vars entry type"):
        plugin.run(ctx)


def test_plugin_repr(plugin):
    assert "env_init" in repr(plugin)
