"""Plugin that generates a .env.example file from template variables."""

from pathlib import Path
from scaffy.plugins.base import BasePlugin, PluginError
from scaffy.plugins.registry import register


class EnvInitPlugin(BasePlugin):
    name = "env_init"

    def run(self, context: dict) -> None:
        """
        Write a .env.example file populated with variable names from the
        template's ``env_vars`` list.  Each entry may be either a plain
        string (key only) or a dict with ``key`` and optional ``default``.

        Context keys used:
            output_dir  – destination directory (Path or str)
            template    – the loaded template dict
        """
        output_dir = Path(context.get("output_dir", "."))
        template = context.get("template", {})
        env_vars = template.get("env_vars", [])

        if not env_vars:
            return

        lines = ["# Auto-generated by scaffy — fill in real values before use", ""]

        for entry in env_vars:
            if isinstance(entry, dict):
                key = entry.get("key", "")
                default = entry.get("default", "")
                if not key:
                    raise PluginError("env_init: env_vars entry missing 'key' field")
                lines.append(f"{key}={default}")
            elif isinstance(entry, str):
                lines.append(f"{entry}=")
            else:
                raise PluginError(
                    f"env_init: unsupported env_vars entry type: {type(entry)}"
                )

        env_path = output_dir / ".env.example"
        try:
            env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        except OSError as exc:
            raise PluginError(f"env_init: could not write .env.example: {exc}") from exc


register(EnvInitPlugin)
